services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=juanvillamil
        - UID=1000
    container_name: leo_counter_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Código de la aplicación
      - .:/var/www/html
      
      #  VOLUMEN PARA ARCHIVOS SUBIDOS DE MOVIMIENTOS
      - movimientos_data:/var/www/html/storage/app/data/movimientos
      
      # Storage completo en volumen 
      - app_storage:/var/www/html/storage
      
      #  LOGS en volumen separado
      - app_logs:/var/www/html/storage/logs
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web 
    restart: unless-stopped

volumes:
  # Archivos de movimientos (PDFs, comprobantes)
  movimientos_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/app/data/movimientos 

  # Storage completo
  app_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage 

  # Logs separados
  app_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/logs

  # Base de datos
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/mysql/data

networks:
  leo_network:
    driver: bridge
